/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AccessDeniedRouteImport } from './routes/access-denied'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RSlugRouteImport } from './routes/r.$slug'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated/orders'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedChangePasswordRouteImport } from './routes/_authenticated/change-password'
import { Route as RSlugBackupRouteImport } from './routes/r.$slug.backup'
import { Route as AuthenticatedOwnerMenuRouteImport } from './routes/_authenticated/owner.menu'
import { Route as AuthenticatedAdminRestaurantsRouteImport } from './routes/_authenticated/admin.restaurants'
import { Route as AuthenticatedAdminMenuTemplatesRouteImport } from './routes/_authenticated/admin/menu-templates'
import { Route as AuthenticatedAdminIntroVideoRouteImport } from './routes/_authenticated/admin.intro-video'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessDeniedRoute = AccessDeniedRouteImport.update({
  id: '/access-denied',
  path: '/access-denied',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RSlugRoute = RSlugRouteImport.update({
  id: '/r/$slug',
  path: '/r/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChangePasswordRoute =
  AuthenticatedChangePasswordRouteImport.update({
    id: '/change-password',
    path: '/change-password',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const RSlugBackupRoute = RSlugBackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => RSlugRoute,
} as any)
const AuthenticatedOwnerMenuRoute = AuthenticatedOwnerMenuRouteImport.update({
  id: '/owner/menu',
  path: '/owner/menu',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRestaurantsRoute =
  AuthenticatedAdminRestaurantsRouteImport.update({
    id: '/admin/restaurants',
    path: '/admin/restaurants',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminMenuTemplatesRoute =
  AuthenticatedAdminMenuTemplatesRouteImport.update({
    id: '/admin/menu-templates',
    path: '/admin/menu-templates',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminIntroVideoRoute =
  AuthenticatedAdminIntroVideoRouteImport.update({
    id: '/admin/intro-video',
    path: '/admin/intro-video',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/auth': typeof AuthRoute
  '/change-password': typeof AuthenticatedChangePasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/r/$slug': typeof RSlugRouteWithChildren
  '/admin/intro-video': typeof AuthenticatedAdminIntroVideoRoute
  '/admin/menu-templates': typeof AuthenticatedAdminMenuTemplatesRoute
  '/admin/restaurants': typeof AuthenticatedAdminRestaurantsRoute
  '/owner/menu': typeof AuthenticatedOwnerMenuRoute
  '/r/$slug/backup': typeof RSlugBackupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/auth': typeof AuthRoute
  '/change-password': typeof AuthenticatedChangePasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/r/$slug': typeof RSlugRouteWithChildren
  '/admin/intro-video': typeof AuthenticatedAdminIntroVideoRoute
  '/admin/menu-templates': typeof AuthenticatedAdminMenuTemplatesRoute
  '/admin/restaurants': typeof AuthenticatedAdminRestaurantsRoute
  '/owner/menu': typeof AuthenticatedOwnerMenuRoute
  '/r/$slug/backup': typeof RSlugBackupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/access-denied': typeof AccessDeniedRoute
  '/auth': typeof AuthRoute
  '/_authenticated/change-password': typeof AuthenticatedChangePasswordRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/orders': typeof AuthenticatedOrdersRoute
  '/r/$slug': typeof RSlugRouteWithChildren
  '/_authenticated/admin/intro-video': typeof AuthenticatedAdminIntroVideoRoute
  '/_authenticated/admin/menu-templates': typeof AuthenticatedAdminMenuTemplatesRoute
  '/_authenticated/admin/restaurants': typeof AuthenticatedAdminRestaurantsRoute
  '/_authenticated/owner/menu': typeof AuthenticatedOwnerMenuRoute
  '/r/$slug/backup': typeof RSlugBackupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access-denied'
    | '/auth'
    | '/change-password'
    | '/dashboard'
    | '/orders'
    | '/r/$slug'
    | '/admin/intro-video'
    | '/admin/menu-templates'
    | '/admin/restaurants'
    | '/owner/menu'
    | '/r/$slug/backup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access-denied'
    | '/auth'
    | '/change-password'
    | '/dashboard'
    | '/orders'
    | '/r/$slug'
    | '/admin/intro-video'
    | '/admin/menu-templates'
    | '/admin/restaurants'
    | '/owner/menu'
    | '/r/$slug/backup'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/access-denied'
    | '/auth'
    | '/_authenticated/change-password'
    | '/_authenticated/dashboard'
    | '/_authenticated/orders'
    | '/r/$slug'
    | '/_authenticated/admin/intro-video'
    | '/_authenticated/admin/menu-templates'
    | '/_authenticated/admin/restaurants'
    | '/_authenticated/owner/menu'
    | '/r/$slug/backup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AccessDeniedRoute: typeof AccessDeniedRoute
  AuthRoute: typeof AuthRoute
  RSlugRoute: typeof RSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-denied': {
      id: '/access-denied'
      path: '/access-denied'
      fullPath: '/access-denied'
      preLoaderRoute: typeof AccessDeniedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$slug': {
      id: '/r/$slug'
      path: '/r/$slug'
      fullPath: '/r/$slug'
      preLoaderRoute: typeof RSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/change-password': {
      id: '/_authenticated/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof AuthenticatedChangePasswordRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/r/$slug/backup': {
      id: '/r/$slug/backup'
      path: '/backup'
      fullPath: '/r/$slug/backup'
      preLoaderRoute: typeof RSlugBackupRouteImport
      parentRoute: typeof RSlugRoute
    }
    '/_authenticated/owner/menu': {
      id: '/_authenticated/owner/menu'
      path: '/owner/menu'
      fullPath: '/owner/menu'
      preLoaderRoute: typeof AuthenticatedOwnerMenuRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/restaurants': {
      id: '/_authenticated/admin/restaurants'
      path: '/admin/restaurants'
      fullPath: '/admin/restaurants'
      preLoaderRoute: typeof AuthenticatedAdminRestaurantsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/menu-templates': {
      id: '/_authenticated/admin/menu-templates'
      path: '/admin/menu-templates'
      fullPath: '/admin/menu-templates'
      preLoaderRoute: typeof AuthenticatedAdminMenuTemplatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/intro-video': {
      id: '/_authenticated/admin/intro-video'
      path: '/admin/intro-video'
      fullPath: '/admin/intro-video'
      preLoaderRoute: typeof AuthenticatedAdminIntroVideoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedChangePasswordRoute: typeof AuthenticatedChangePasswordRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRoute
  AuthenticatedAdminIntroVideoRoute: typeof AuthenticatedAdminIntroVideoRoute
  AuthenticatedAdminMenuTemplatesRoute: typeof AuthenticatedAdminMenuTemplatesRoute
  AuthenticatedAdminRestaurantsRoute: typeof AuthenticatedAdminRestaurantsRoute
  AuthenticatedOwnerMenuRoute: typeof AuthenticatedOwnerMenuRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedChangePasswordRoute: AuthenticatedChangePasswordRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedOrdersRoute: AuthenticatedOrdersRoute,
  AuthenticatedAdminIntroVideoRoute: AuthenticatedAdminIntroVideoRoute,
  AuthenticatedAdminMenuTemplatesRoute: AuthenticatedAdminMenuTemplatesRoute,
  AuthenticatedAdminRestaurantsRoute: AuthenticatedAdminRestaurantsRoute,
  AuthenticatedOwnerMenuRoute: AuthenticatedOwnerMenuRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface RSlugRouteChildren {
  RSlugBackupRoute: typeof RSlugBackupRoute
}

const RSlugRouteChildren: RSlugRouteChildren = {
  RSlugBackupRoute: RSlugBackupRoute,
}

const RSlugRouteWithChildren = RSlugRoute._addFileChildren(RSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AccessDeniedRoute: AccessDeniedRoute,
  AuthRoute: AuthRoute,
  RSlugRoute: RSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
